# Author: BeiYu
# Github: https://github.com/beiyuouo
# Date  : 2021/1/12 17:10
# Description:

ALKAID_HOST = ''

ALKAID_CAPTURE_SUBSCRIBE_SSR_API = ALKAID_HOST + ""
ALKAID_CAPTURE_SUBSCRIBE_V2RAY_API = ALKAID_HOST + ""
ALKAID_VERSION_MANAGER_API = ALKAID_HOST + ""
ALKAID_GET_SUBS_NUM_API = ALKAID_HOST + ""
